class Categories {}

const List<String> categoryList = [
  "Architecture and Engineering",
  "Arts Design Entertainment Sports and Media",
  "Building and Grounds Cleaning and Maintenance",
  "Business and Financial Operations",
  "Community and Social Services",
  "Computer and Mathematics",
  "Construction and Extraction",
  "Education Training and Library",
  "Farming Fishing and Forestry",
  "Food Preparation and Serving Related",
  "Healthcare Practitioners and Technical",
  "Healthcare Support",
  "Installation Maintenance and Repair",
  "Legal",
  "Life Physical and Social Science",
  "Management",
  "Office and Administrative Support",
  "Personal Care and Service",
  "Production",
  "Protective Service",
  "Sales and Related",
  "Other",
];
const List<List<String>> subCategoryList = [
  [
    "Aerospace Engineering and Operations Technicians",
    "Aerospace Engineers",
    "Agricultural Engineers",
    "Architects, Except Landscape and Naval",
    "Architectural and Civil Drafters",
    "Architectural Drafters",
    "Automotive Engineering Technicians",
    "Automotive Engineers",
    "Biochemical Engineers",
    "Biomedical Engineers",
    "Cartographers and Photogrammetrists",
    "Chemical Engineers",
    "Civil Drafters",
    "Civil Engineering Technicians",
    "Civil Engineers",
    "Computer Hardware Engineers",
    "Drafters, All Other",
    "Electrical and Electronic Engineering Technicians",
    "Electrical and Electronics Drafters",
    "Electrical Drafters",
    "Electrical Engineering Technicians",
    "Electrical Engineering Technologists",
    "Electrical Engineers",
    "Electro-Mechanical Technicians",
    "Electromechanical Engineering Technologists",
    "Electronic Drafters",
    "Electronics Engineering Technicians",
    "Electronics Engineering Technologists",
    "Electronics Engineers, Except Computer",
    "Energy Engineers",
    "Engineering Technicians, Except Drafters, All Other",
    "Engineers, All Other",
    "Environmental Engineering Technicians",
    "Environmental Engineers",
    "Fire-Prevention and Protection Engineers",
    "Fuel Cell Engineers",
    "Fuel Cell Technicians",
    "Geodetic Surveyors",
    "Health and Safety Engineers, Except Mining Safety Engineers and Inspectors",
    "Human Factors Engineers and Ergonomists",
    "Industrial Engineering Technicians",
    "Industrial Engineering Technologists",
    "Industrial Engineers",
    "Industrial Safety and Health Engineers",
    "Landscape Architects",
    "Manufacturing Engineering Technologists",
    "Manufacturing Engineers",
    "Manufacturing Production Technicians",
    "Mapping Technicians",
    "Marine Architects",
    "Marine Engineers",
    "Marine Engineers and Naval Architects",
    "Materials Engineers",
    "Mechanical Drafters",
    "Mechanical Engineering Technicians",
    "Mechanical Engineering Technologists",
    "Mechanical Engineers",
    "Mechatronics Engineers",
    "Microsystems Engineers",
    "Mining and Geological Engineers, Including Mining Safety Engineers",
    "Nanosystems Engineers",
    "Nanotechnology Engineering Technicians",
    "Nanotechnology Engineering Technologists",
    "Non-Destructive Testing Specialists",
    "Nuclear Engineers",
    "Petroleum Engineers",
    "Photonics Engineers",
    "Photonics Technicians",
    "Product Safety Engineers",
    "Radio Frequency Identification Device Specialists",
    "Robotics Engineers",
    "Robotics Technicians",
    "Solar Energy Systems Engineers",
    "Surveying and Mapping Technicians",
    "Surveying Technicians",
    "Surveyors",
    "Transportation Engineers",
    "Validation Engineers",
    "Water/Wastewater Engineers",
    "Wind Energy Engineers"
  ],
  ["0", "1", "2"],
  ["a", "b", "c"],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];
