class Locations {}

const provinceArabNameList = [
  "أدرار",
  "الشلف",
  "الأغواط",
  "أم البواقي",
  "باتنة",
  "بجاية",
  "بسكرة",
  "بشار",
  "البليدة",
  "البويرة",
  "تمنراست",
  "تبسة",
  "تلمسان",
  "تيارت",
  "تيزي وزو",
  "الجزائر",
  "الجلفة",
  "جيجل",
  "سطيف",
  "سعيدة",
  "سكيكدة",
  "سيدي بلعباس",
  "عنابة",
  "قالمة",
  "قسنطينة",
  "المدية",
  "مستغانم",
  "المسيلة",
  "معسكر",
  "ورقلة",
  "وهران",
  "البيض",
  "إليزي",
  "برج بوعريريج",
  "بومرداس",
  "الطارف",
  "تندوف",
  "تيسمسيلت",
  "الوادي",
  "خنشلة",
  "سوق أهراس",
  "تيبازة",
  "ميلة",
  "عين الدفلى",
  "النعامة",
  "عين تموشنت",
  "غرداية",
  "غليزان",
];

const provinceLatinNameList = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Bechar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tbessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Se9tif",
  "Saefda",
  "Skikda",
  "Sidi Bel Abbes",
  "Annaba",
  "Guelma",
  "Constantine",
  "Medea",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arreridj",
  "Boumerdes",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Ain Defla",
  "Naama",
  "Ain Temouchent",
  "Ghardaefa",
  "Relizane",
];

List<List<String>> communeLatinNameList = [
  [
    "Adrar",
    "Tamest",
    "Charouine",
    "Reggane",
    "In Zghmir",
    "Tit",
    "Ksar Kaddour",
    "Tsabit",
    "Timimoun",
    "Ouled Said",
    "Zaouiet Kounta",
    "Aoulef",
    "Timokten",
    "Tamentit",
    "Fenoughil",
    "Tinerkouk",
    "Deldoul",
    "Sali",
    "Akabli",
    "Metarfa",
    "Ouled Ahmed Tammi",
    "Bouda",
    "Aougrout",
    "Talmine",
    "Bordj Badji Mokhtar",
    "Sbaa",
    "Ouled Aissa",
    "Timiaouine",
  ],
  [
    "Chlef",
    "Tenes",
    "Benairia",
    "El Karimia",
    "Tadjna",
    "Taougrite",
    "Beni Haoua",
    "Sobha",
    "Harchoun",
    "Ouled Fares",
    "Sidi Akacha",
    "Boukadir",
    "Beni Rached",
    "Talassa",
    "Herenfa",
    "Oued Goussine",
    "Dahra",
    "Ouled Abbes",
    "Sendjas",
    "Zeboudja",
    "Oued Sly",
    "Abou El Hassen",
    "El Marsa",
    "Chettia",
    "Sidi Abderrahmane",
    "Moussadek",
    "El Hadjadj",
    "Labiod Medjadja",
    "Oued Fodda",
    "Ouled Ben Abdelkader",
    "Bouzghaia",
    "Ain Merane",
    "Oum Drou",
    "Breira",
    "Beni Bouateb",
  ],
  [
    "Laghouat",
    "Ksar El Hirane",
    "Benacer Ben Chohra",
    "Sidi Makhlouf",
    "Hassi Delaa",
    "Hassi R'Mel",
    "Ain Mahdi",
    "Tadjmout",
    "El Kheneg",
    "Gueltat Sidi Saad",
    "Ain Sidi Ali",
    "Beidha",
    "Brida",
    "El Ghicha",
    "Hadj Mechri",
    "Sebgag",
    "Taouiala",
    "Tadjrouna",
    "Aflou",
    "El Assafia",
    "Oued Morra",
    "Oued M'Zi",
    "El Haouaita",
    "Sidi Bouzid",
  ],
  [
    "Oum El Bouaghi",
    "Ain Beida",
    "Ain M'lila",
    "Behir Chergui",
    "El Amiria",
    "Sigus",
    "El Belala",
    "Ain Babouche",
    "Berriche",
    "Ouled Hamla",
    "Dhala",
    "Ain Kercha",
    "Hanchir Toumghani",
    "El Djazia",
    "Ain Diss",
    "Fkirina",
    "Souk Naamane",
    "Zorg",
    "El Fedjoudj Boughrara Saoudi",
    "Ouled Zouai",
    "Bir Chouhada",
    "Ksar Sbahi",
    "Oued Nini",
    "Meskiana",
    "Ain Fekroune",
    "Rahia",
    "Ain Zitoun",
    "Ouled Gacem",
    "El Harmilia",
  ],
  [
    "Batna",
    "Ghassira",
    "Maafa",
    "Merouana",
    "Seriana",
    "Menaa",
    "El Madher",
    "Tazoult",
    "Ngaous",
    "Guigba",
    "Inoughissen",
    "Ouyoun El Assafir",
    "Djerma",
    "Bitam",
    "Metkaouak",
    "Arris",
    "Kimmel",
    "Tilatou",
    "Ain Djasser",
    "Ouled Selam",
    "Tigherghar",
    "Ain Yagout",
    "Fesdis",
    "Sefiane",
    "Rahbat",
    "Tighanimine",
    "Lemsane",
    "Ksar Belezma",
    "Seggana",
    "Ichmoul",
    "Foum Toub",
    "Beni Foudhala El Hakania",
    "Oued El Ma",
    "Talkhamt",
    "Bouzina",
    "Chemora",
    "Oued Chaaba",
    "Taxlent",
    "Gosbat",
    "Ouled Aouf",
    "Boumagueur",
    "Barika",
    "Djezzar",
    "Tkout",
    "Ain Touta",
    "Hidoussa",
    "Teniet El Abed",
    "Oued Taga",
    "Ouled Fadel",
    "Timgad",
    "Ras El Aioun",
    "Chir",
    "Ouled Si Slimane",
    "Zanat El Beida",
    "M'doukel",
    "Ouled Ammar",
    "El Hassi",
    "Lazrou",
    "Boumia",
    "Boulhilat",
    "Larbaa",
  ],
  [
    "Bejaia",
    "Amizour",
    "Ferraoun",
    "Taourirt Ighil",
    "Chelata",
    "Tamokra",
    "Timzrit",
    "Souk El Thenine",
    "M'cisna",
    "Thinabdher",
    "Tichi",
    "Semaoun",
    "Kendira",
    "Tifra",
    "Ighram",
    "Amalou",
    "Ighil Ali",
    "Ifelain Ilmathen",
    "Toudja",
    "Darguina",
    "Sidi Ayad",
    "Aokas",
    "Ait Djellil",
    "Adekar",
    "Akbou",
    "Seddouk",
    "Tazmalt",
    "Ait R'zine",
    "Chemini",
    "Souk Oufella",
    "Taskriout",
    "Tibane",
    "Tala Hamza",
    "Barbacha",
    "Beni Ksila",
    "Ouzallaguen",
    "Bouhamza",
    "Beni Melikeche",
    "Sidi Aich",
    "El Kseur",
    "Melbou",
    "Akfadou",
    "Leflaye",
    "Kherrata",
    "Draa Kaid",
    "Tamridjet",
    "Ait Smail",
    "Boukhelifa",
    "Tizi N'berber",
    "Beni Maouch",
    "Oued Ghir",
    "Boudjellil",
  ],
  [
    "Biskra",
    "Oumache",
    "Branis",
    "Chetma",
    "Ouled Djellal",
    "Ras El Miaad",
    "Besbes",
    "Sidi Khaled",
    "Doucen",
    "Ech Chaiba",
    "Sidi Okba",
    "Mchouneche",
    "El Haouch",
    "Ain Naga",
    "Zeribet El Oued",
    "El Feidh",
    "El Kantara",
    "Ain Zaatout",
    "El Outaya",
    "Djemorah",
    "Tolga",
    "Lioua",
    "Lichana",
    "Ourlal",
    "M'lili",
    "Foughala",
    "Bordj Ben Azzouz",
    "M'ziraa",
    "Bouchagroun",
    "Mekhadma",
    "El Ghrous",
    "El Hadjab",
    "Khanguet Sidinadji",
  ],
  [
    "Bechar",
    "Erg Ferradj",
    "Ouled Khoudir",
    "Meridja",
    "Timoudi",
    "Lahmar",
    "Beni Abbes",
    "Beni Ikhlef",
    "Mechraa Houari Boumedienne",
    "Kenedsa",
    "Igli",
    "Tabalbala",
    "Taghit",
    "El Ouata",
    "Boukais",
    "Mogheul",
    "Abadla",
    "Kerzaz",
    "Ksabi",
    "Tamtert",
    "Beni Ounif",
  ],
  [
    "Blida",
    "Chebli",
    "Bouinan",
    "Oued El Alleug",
    "Ouled Yaich",
    "Chrea",
    "El Affroun",
    "Chiffa",
    "Hammam Melouane",
    "Ben Khlil",
    "Soumaa",
    "Mouzaia",
    "Souhane",
    "Meftah",
    "Ouled Selama",
    "Boufarik",
    "Larbaa",
    "Oued Djer",
    "Beni Tamou",
    "Bouarfa",
    "Beni Mered",
    "Bougara",
    "Guerrouaou",
    "Ain Romana",
    "Djebabra",
  ],
  [
    "Bouira",
    "El Asnam",
    "Guerrouma",
    "Souk El Khemis",
    "Kadiria",
    "Hanif",
    "Dirah",
    "Ait Laaziz",
    "Taghzout",
    "Raouraoua",
    "Mezdour",
    "Haizer",
    "Lakhdaria",
    "Maala",
    "El Hachimia",
    "Aomar",
    "Chorfa",
    "Bordj Oukhriss",
    "El Adjiba",
    "El Hakimia",
    "El Khebouzia",
    "Ahl El Ksar",
    "Bouderbala",
    "Zbarbar",
    "Ain El Hadjar",
    "Djebahia",
    "Aghbalou",
    "Taguedit",
    "Ain Turk",
    "Saharidj",
    "Dechmia",
    "Ridane",
    "Bechloul",
    "Boukram",
    "Ain Bessam",
    "Bir Ghbalou",
    "Mchedallah",
    "Sour El Ghozlane",
    "Maamora",
    "Ouled Rached",
    "Ain Laloui",
    "Hadjera Zerga",
    "Ath Mansour",
    "El Mokrani",
    "Oued El Berdi",
  ],
  [
    "Tamanghasset",
    "Abalessa",
    "In Ghar",
    "In Guezzam",
    "Idles",
    "Tazouk",
    "Tinzaouatine",
    "In Salah",
    "In Amguel",
    "Foggaret Ezzaouia",
  ],
  [
    "Tebessa",
    "Bir El Ater",
    "Cheria",
    "Stah Guentis",
    "El Aouinet",
    "Lahouidjbet",
    "Safsaf El Ouesra",
    "Hammamet",
    "Negrine",
    "Bir El Mokadem",
    "El Kouif",
    "Morsott",
    "El Ogla",
    "Bir Dheb",
    "El Ogla",
    "Gorriguer",
    "Bekkaria",
    "Boukhadra",
    "Ouenza",
    "El Ma El Biodh",
    "Oum Ali",
    "Tlidjene",
    "Ain Zerga",
    "El Meridj",
    "Boulhaf Dyr",
    "Bedjene",
    "El Mazeraa",
    "Ferkane",
  ],
  [
    "Tlemcen",
    "Beni Mester",
    "Ain Tallout",
    "Remchi",
    "El Fehoul",
    "Sabra",
    "Ghazaouet",
    "Souani",
    "Djebala",
    "El Gor",
    "Oued Chouly",
    "Ain Fezza",
    "Ouled Mimoun",
    "Amieur",
    "Ain Youcef",
    "Zenata",
    "Beni Snous",
    "Bab El Assa",
    "Dar Yaghmouracene",
    "Fellaoucene",
    "Azails",
    "Sebbaa Chioukh",
    "Terni Beni Hediel",
    "Bensekrane",
    "Ain Nehala",
    "Hennaya",
    "Maghnia",
    "Hammam Boughrara",
    "Souahlia",
    "Msirda Fouaga",
    "Ain Fetah",
    "El Aricha",
    "Souk Thlata",
    "Sidi Abdelli",
    "Sebdou",
    "Beni Ouarsous",
    "Sidi Medjahed",
    "Beni Boussaid",
    "Marsa Ben Mhidi",
    "Nedroma",
    "Sidi Djillali",
    "Beni Bahdel",
    "El Bouihi",
    "Honaine",
    "Tianet",
    "Ouled Riyah",
    "Bouhlou",
    "Souk El Khemis",
    "Ain Ghoraba",
    "Chetouane",
    "Mansourah",
    "Beni Semiel",
    "Ain Kebira",
  ],
  [
    "Tiaret",
    "Medroussa",
    "Ain Bouchekif",
    "Sidi Ali Mellal",
    "Ain Zarit",
    "Ain Deheb",
    "Sidi Bakhti",
    "Medrissa",
    "Zmalet El Emir Aek",
    "Madna",
    "Sebt",
    "Mellakou",
    "Dahmouni",
    "Rahouia",
    "Mahdia",
    "Sougueur",
    "Sidi Abdelghani",
    "Ain El Hadid",
    "Ouled Djerad",
    "Naima",
    "Meghila",
    "Guertoufa",
    "Sidi Hosni",
    "Djillali Ben Amar",
    "Sebaine",
    "Tousnina",
    "Frenda",
    "Ain Kermes",
    "Ksar Chellala",
    "Rechaiga",
    "Nadorah",
    "Tagdemt",
    "Oued Lilli",
    "Mechraa Safa",
    "Hamadia",
    "Chehaima",
    "Takhemaret",
    "Sidi Abderrahmane",
    "Serghine",
    "Bougara",
    "Faidja",
    "Tidda",
  ],
  [
    "Tizi Ouzou",
    "Ain El Hammam",
    "Akbil",
    "Freha",
    "Souamaa",
    "Mechtrass",
    "Irdjen",
    "Timizart",
    "Makouda",
    "Draa El Mizan",
    "Tizi Ghenif",
    "Bounouh",
    "Ait Chaffaa",
    "Frikat",
    "Beni Aissi",
    "Beni Zmenzer",
    "Iferhounene",
    "Azazga",
    "Iloula Oumalou",
    "Yakouren",
    "Larba Nait Irathen",
    "Tizi Rached",
    "Zekri",
    "Ouaguenoun",
    "Ain Zaouia",
    "Mkira",
    "Ait Yahia",
    "Ait Mahmoud",
    "Maatka",
    "Ait Boumehdi",
    "Abi Youcef",
    "Beni Douala",
    "Illilten",
    "Bouzguen",
    "Ait Aggouacha",
    "Ouadhia",
    "Azzefoun",
    "Tigzirt",
    "Ait Aissa Mimoun",
    "Boghni",
    "Ifigha",
    "Ait Oumalou",
    "Tirmitine",
    "Akerrou",
    "Yatafen",
    "Beni Ziki",
    "Draa Ben Khedda",
    "Ouacif",
    "Idjeur",
    "Mekla",
    "Tizi Nthlata",
    "Beni Yenni",
    "Aghrib",
    "Iflissen",
    "Boudjima",
    "Ait Yahia Moussa",
    "Souk El Thenine",
    "Ait Khelil",
    "Sidi Naamane",
    "Iboudraren",
    "Agouni Gueghrane",
    "Mizrana",
    "Imsouhal",
    "Tadmait",
    "Ait Bouadou",
    "Assi Youcef",
    "Ait Toudert",
  ],
  [
    "Alger Centre",
    "Sidi Mhamed",
    "El Madania",
    "Belouizdad",
    "Bab El Oued",
    "Bologhine",
    "Casbah",
    "Oued Koriche",
    "Bir Mourad Rais",
    "El Biar",
    "Bouzareah",
    "Birkhadem",
    "El Harrach",
    "Baraki",
    "Oued Smar",
    "Bourouba",
    "Hussein Dey",
    "Kouba",
    "Bachedjerah",
    "Dar El Beida",
    "Bab Azzouar",
    "Ben Aknoun",
    "Dely Ibrahim",
    "El Hammamet",
    "Rais Hamidou",
    "Djasr Kasentina",
    "El Mouradia",
    "Hydra",
    "Mohammadia",
    "Bordj El Kiffan",
    "El Magharia",
    "Beni Messous",
    "Les Eucalyptus",
    "Birtouta",
    "Tassala El Merdja",
    "Ouled Chebel",
    "Sidi Moussa",
    "Ain Taya",
    "Bordj El Bahri",
    "Marsa",
    "Haraoua",
    "Rouiba",
    "Reghaia",
    "Ain Benian",
    "Staoueli",
    "Zeralda",
    "Mahelma",
    "Rahmania",
    "Souidania",
    "Cheraga",
    "Ouled Fayet",
    "El Achour",
    "Draria",
    "Douera",
    "Baba Hassen",
    "Khracia",
    "Saoula",
  ],
  [
    "Djelfa",
    "Moudjebara",
    "El Guedid",
    "Hassi Bahbah",
    "Ain Maabed",
    "Sed Rahal",
    "Feidh El Botma",
    "Birine",
    "Bouira Lahdeb",
    "Zaccar",
    "El Khemis",
    "Sidi Baizid",
    "M'Liliha",
    "El Idrissia",
    "Douis",
    "Hassi El Euch",
    "Messaad",
    "Guettara",
    "Sidi Ladjel",
    "Had Sahary",
    "Guernini",
    "Selmana",
    "Ain Chouhada",
    "Oum Laadham",
    "Dar Chouikh",
    "Charef",
    "Beni Yacoub",
    "Zaafrane",
    "Deldoul",
    "Ain El Ibel",
    "Ain Oussera",
    "Benhar",
    "Hassi Fedoul",
    "Amourah",
    "Ain Fekka",
    "Tadmit",
  ],
  [
    "Jijel",
    "Erraguene",
    "El Aouana",
    "Ziamma Mansouriah",
    "Taher",
    "Emir Abdelkader",
    "Chekfa",
    "Chahna",
    "El Milia",
    "Sidi Maarouf",
    "Settara",
    "El Ancer",
    "Sidi Abdelaziz",
    "Kaous",
    "Ghebala",
    "Bouraoui Belhadef",
    "Djmila",
    "Selma Benziada",
    "Boussif Ouled Askeur",
    "El Kennar Nouchfi",
    "Ouled Yahia Khadrouch",
    "Boudria Beni Yadjis",
    "Kemir Oued Adjoul",
    "Texena",
    "Djemaa Beni Habibi",
    "Bordj T'her",
    "Ouled Rabah",
    "Ouadjana",
  ],
  [
    "Setif",
    "Ain El Kebira",
    "Beni Aziz",
    "Ouled Sidi Ahmed",
    "Boutaleb",
    "Ain Roua",
    "Draa Kebila",
    "Bir El Arch",
    "Beni Chebana",
    "Ouled Tebben",
    "Hamma",
    "Maaouia",
    "Ain Legraj",
    "Ain Abessa",
    "Dehamcha",
    "Babor",
    "Guidjel",
    "Ain Lahdjar",
    "Bousselam",
    "El Eulma",
    "Djemila",
    "Beni Ouartilane",
    "Rosfa",
    "Ouled Addouane",
    "Belaa",
    "Ain Arnat",
    "Amoucha",
    "Ain Oulmane",
    "Beidha Bordj",
    "Bouandas",
    "Bazer Sakhra",
    "Hammam Essokhna",
    "Mezloug",
    "Bir Haddada",
    "Serdj El Ghoul",
    "Harbil",
    "El Ouricia",
    "Tizi Nbechar",
    "Salah Bey",
    "Ain Azal",
    "Guenzet",
    "Talaifacene",
    "Bougaa",
    "Beni Fouda",
    "Tachouda",
    "Beni Mouhli",
    "Ouled Sabor",
    "Guellal",
    "Ain Sebt",
    "Hammam Guergour",
    "Ait Naoual Mezada",
    "Ksar El Abtal",
    "Beni Hocine",
    "Ait Tizi",
    "Maouklane",
    "Guelta Zerka",
    "Oued El Barad",
    "Taya",
    "El Ouldja",
    "Tella",
  ],
  [
    "Saida",
    "Doui Thabet",
    "Ain El Hadjar",
    "Ouled Khaled",
    "Moulay Larbi",
    "Youb",
    "Hounet",
    "Sidi Amar",
    "Sidi Boubekeur",
    "El Hassasna",
    "Maamora",
    "Sidi Ahmed",
    "Ain Sekhouna",
    "Ouled Brahim",
    "Tircine",
    "Ain Soltane",
  ],
  [
    "Skikda",
    "Ain Zouit",
    "El Hadaik",
    "Azzaba",
    "Djendel",
    "Ain Cherchar",
    "Bekkouche Lakhdar",
    "Ben Azzouz",
    "Es Sebt",
    "Collo",
    "Beni Zid",
    "Kerkera",
    "Ouled Attia",
    "Oued Zehour",
    "Zitouna",
    "El Harrouch",
    "Zerdazas",
    "Ouled Hebaba",
    "Sidi Mezghiche",
    "Emdjez Edchich",
    "Beni Oulbane",
    "Ain Bouziane",
    "Ramdane Djamel",
    "Beni Bachir",
    "Salah Bouchaour",
    "Tamalous",
    "Ain Kechra",
    "Oum Toub",
    "Bein El Ouiden",
    "Filfila",
    "Cheraia",
    "Kanoua",
    "El Ghedir",
    "Bouchtata",
    "Ouldja Boulbalout",
    "Kheneg Mayoum",
    "Hamadi Krouma",
    "El Marsa",
  ],
  [
    "Sidi Bel Abbes",
    "Tessala",
    "Sidi Brahim",
    "Mostefa Ben Brahim",
    "Telagh",
    "Mezaourou",
    "Boukhanafis",
    "Sidi Ali Boussidi",
    "Badredine El Mokrani",
    "Marhoum",
    "Tafissour",
    "Amarnas",
    "Tilmouni",
    "Sidi Lahcene",
    "Ain Thrid",
    "Makedra",
    "Tenira",
    "Moulay Slissen",
    "El Hacaiba",
    "Hassi Zehana",
    "Tabia",
    "Merine",
    "Ras El Ma",
    "Ain Tindamine",
    "Ain Kada",
    "Mcid",
    "Sidi Khaled",
    "Ain El Berd",
    "Sfissef",
    "Ain Adden",
    "Oued Taourira",
    "Dhaya",
    "Zerouala",
    "Lamtar",
    "Sidi Chaib",
    "Sidi Dahou",
    "Oued Sbaa",
    "Boudjebaa El Bordj",
    "Sehala Thaoura",
    "Sidi Yacoub",
    "Sidi Hamadouche",
    "Belarbi",
    "Oued Sefioun",
    "Teghalimet",
    "Ben Badis",
    "Sidi Ali Benyoub",
    "Chetouane Belaila",
    "Bir El Hammam",
    "Taoudmout",
    "Redjem Demouche",
    "Benachiba Chelia",
    "Hassi Dahou",
  ],
  [
    "Annaba",
    "Berrahel",
    "El Hadjar",
    "Eulma",
    "El Bouni",
    "Oued El Aneb",
    "Cheurfa",
    "Seraidi",
    "Ain Berda",
    "Chetaibi",
    "Sidi Amer",
    "Treat",
  ],
  [
    "Guelma",
    "Nechmaya",
    "Bouati Mahmoud",
    "Oued Zenati",
    "Tamlouka",
    "Oued Fragha",
    "Ain Sandel",
    "Ras El Agba",
    "Dahouara",
    "Belkhir",
    "Ben Djarah",
    "Bou Hamdane",
    "Ain Makhlouf",
    "Ain Ben Beida",
    "Khezara",
    "Beni Mezline",
    "Bou Hachana",
    "Guelaat Bou Sbaa",
    "Hammam Maskhoutine",
    "El Fedjoudj",
    "Bordj Sabat",
    "Hamman Nbail",
    "Ain Larbi",
    "Medjez Amar",
    "Bouchegouf",
    "Heliopolis",
    "Houari Boumediene",
    "Roknia",
    "Salaoua Announa",
    "Medjez Sfa",
    "Boumahra Ahmed",
    "Ain Reggada",
    "Oued Cheham",
    "Djeballah Khemissi",
  ],
  [
    "Constantine",
    "Hamma Bouziane",
    "Ibn Badis",
    "Zighoud Youcef",
    "Didouche Mourad",
    "El Khroub",
    "Ain Abid",
    "Beni Hamiden",
    "Ouled Rahmoune",
    "Ain Smara",
    "Mesaoud Boudjeriou",
    "Ibn Ziad",
  ],
  [
    "Medea",
    "Ouzera",
    "Ouled Maaref",
    "Ain Boucif",
    "Aissaouia",
    "Ouled Deide",
    "El Omaria",
    "Derrag",
    "El Guelbelkebir",
    "Bouaiche",
    "Mezerena",
    "Ouled Brahim",
    "Tizi Mahdi",
    "Sidi Ziane",
    "Tamesguida",
    "El Hamdania",
    "Kef Lakhdar",
    "Chelalet El Adhaoura",
    "Bouskene",
    "Rebaia",
    "Bouchrahil",
    "Ouled Hellal",
    "Tafraout",
    "Baata",
    "Boghar",
    "Sidi Naamane",
    "Ouled Bouachra",
    "Sidi Zahar",
    "Oued Harbil",
    "Benchicao",
    "Sidi Damed",
    "Aziz",
    "Souagui",
    "Zoubiria",
    "Ksar El Boukhari",
    "El Azizia",
    "Djouab",
    "Chahbounia",
    "Meghraoua",
    "Cheniguel",
    "Ain Ouksir",
    "Oum El Djalil",
    "Ouamri",
    "Si Mahdjoub",
    "Tlatet Eddouair",
    "Beni Slimane",
    "Berrouaghia",
    "Seghouane",
    "Meftaha",
    "Mihoub",
    "Boughezoul",
    "Tablat",
    "Deux Bassins",
    "Draa Essamar",
    "Sidi Errabia",
    "Bir Ben Laabed",
    "El Ouinet",
    "Ouled Antar",
    "Bouaichoune",
    "Hannacha",
    "Sedraia",
    "Medjebar",
    "Khams Djouamaa",
    "Saneg",
  ],
  [
    "Mostaganem",
    "Sayada",
    "Fornaka",
    "Stidia",
    "Ain Nouissy",
    "Hassi Maameche",
    "Ain Tadles",
    "Sour",
    "Oued El Kheir",
    "Sidi Bellater",
    "Kheiredine",
    "Sidi Ali",
    "Abdelmalek Ramdane",
    "Hadjadj",
    "Nekmaria",
    "Sidi Lakhdar",
    "Achaacha",
    "Khadra",
    "Bouguirat",
    "Sirat",
    "Ain Sidi Cherif",
    "Mesra",
    "Mansourah",
    "Souaflia",
    "Ouled Boughalem",
    "Ouled Maallah",
    "Mezghrane",
    "Ain Boudinar",
    "Tazgait",
    "Safsaf",
    "Touahria",
    "El Hassiane",
  ],
  [
    "Msila",
    "Maadid",
    "Hammam Dhalaa",
    "Ouled Derradj",
    "Tarmount",
    "Mtarfa",
    "Khoubana",
    "M'cif",
    "Chellal",
    "Ouled Madhi",
    "Magra",
    "Berhoum",
    "Ain Khadra",
    "Ouled Addi Guebala",
    "Belaiba",
    "Sidi Aissa",
    "Ain El Hadjel",
    "Sidi Hadjeres",
    "Ouanougha",
    "Bou Saada",
    "Ouled Sidi Brahim",
    "Sidi Ameur",
    "Tamsa",
    "Ben Srour",
    "Ouled Slimane",
    "El Houamed",
    "El Hamel",
    "Ouled Mansour",
    "Maarif",
    "Dehahna",
    "Bouti Sayah",
    "Khettouti Sed Djir",
    "Zarzour",
    "Oued Chair",
    "Benzouh",
    "Bir Foda",
    "Ain Fares",
    "Sidi Mhamed",
    "Ouled Atia",
    "Souamaa",
    "Ain El Melh",
    "Medjedel",
    "Slim",
    "Ain Errich",
    "Beni Ilmane",
    "Oultene",
    "Djebel Messaad",
  ],
  [
    "Mascara",
    "Bou Hanifia",
    "Tizi",
    "Hacine",
    "Maoussa",
    "Teghennif",
    "El Hachem",
    "Sidi Kada",
    "Zelmata",
    "Oued El Abtal",
    "Ain Ferah",
    "Ghriss",
    "Froha",
    "Matemore",
    "Makdha",
    "Sidi Boussaid",
    "El Bordj",
    "Ain Fekan",
    "Benian",
    "Khalouia",
    "El Menaouer",
    "Oued Taria",
    "Aouf",
    "Ain Fares",
    "Ain Frass",
    "Sig",
    "Oggaz",
    "Alaimia",
    "El Gaada",
    "Zahana",
    "Mohammadia",
    "Sidi Abdelmoumene",
    "Ferraguig",
    "El Ghomri",
    "Sedjerara",
    "Moctadouz",
    "Bou Henni",
    "Guettena",
    "El Mamounia",
    "El Keurt",
    "Gharrous",
    "Gherdjoum",
    "Chorfa",
    "Ras Ain Amirouche",
    "Nesmot",
    "Sidi Abdeldjebar",
    "Sehailia",
  ],
  [
    "Ouargla",
    "Ain Beida",
    "Ngoussa",
    "Hassi Messaoud",
    "Rouissat",
    "Balidat Ameur",
    "Tebesbest",
    "Nezla",
    "Zaouia El Abidia",
    "Sidi Slimane",
    "Sidi Khouiled",
    "Hassi Ben Abdellah",
    "Touggourt",
    "El Hadjira",
    "Taibet",
    "Tamacine",
    "Benaceur",
    "Mnaguer",
    "Megarine",
    "El Allia",
    "El Borma",
  ],
  [
    "Oran",
    "Gdyel",
    "Bir El Djir",
    "Hassi Bounif",
    "Es Senia",
    "Arzew",
    "Bethioua",
    "Marsat El Hadjadj",
    "Ain Turk",
    "El Ancar",
    "Oued Tlelat",
    "Tafraoui",
    "Sidi Chami",
    "Boufatis",
    "Mers El Kebir",
    "Bousfer",
    "El Karma",
    "El Braya",
    "Hassi Ben Okba",
    "Ben Freha",
    "Hassi Mefsoukh",
    "Sidi Ben Yabka",
    "Messerghin",
    "Boutlelis",
    "Ain Kerma",
    "Ain Biya",
  ],
  [
    "El Bayadh",
    "Rogassa",
    "Stitten",
    "Brezina",
    "Ghassoul",
    "Boualem",
    "El Abiodh Sidi Cheikh",
    "Ain El Orak",
    "Arbaouat",
    "Bougtoub",
    "El Kheither",
    "Kef El Ahmar",
    "Boussemghoun",
    "Chellala",
    "Krakda",
    "El Bnoud",
    "Cheguig",
    "Sidi Ameur",
    "El Mehara",
    "Tousmouline",
    "Sidi Slimane",
    "Sidi Tifour",
  ],
  [
    "Illizi",
    "Djanet",
    "Debdeb",
    "Bordj Omar Driss",
    "Bordj El Haouasse",
    "In Amenas",
  ],
  [
    "Bordj Bou Arreridj",
    "Ras El Oued",
    "Bordj Zemoura",
    "Mansoura",
    "El Mhir",
    "Ben Daoud",
    "El Achir",
    "Ain Taghrout",
    "Bordj Ghdir",
    "Sidi Embarek",
    "El Hamadia",
    "Belimour",
    "Medjana",
    "Teniet En Nasr",
    "Djaafra",
    "El Main",
    "Ouled Brahem",
    "Ouled Dahmane",
    "Hasnaoua",
    "Khelil",
    "Taglait",
    "Ksour",
    "Ouled Sidi Brahim",
    "Tafreg",
    "Colla",
    "Tixter",
    "El Ach",
    "El Anseur",
    "Tesmart",
    "Ain Tesra",
    "Bir Kasdali",
    "Ghilassa",
    "Rabta",
    "Haraza",
  ],
  [
    "Boumerdes",
    "Boudouaou",
    "Afir",
    "Bordj Menaiel",
    "Baghlia",
    "Sidi Daoud",
    "Naciria",
    "Djinet",
    "Isser",
    "Zemmouri",
    "Si Mustapha",
    "Tidjelabine",
    "Chabet El Ameur",
    "Thenia",
    "Timezrit",
    "Corso",
    "Ouled Moussa",
    "Larbatache",
    "Bouzegza Keddara",
    "Taourga",
    "Ouled Aissa",
    "Ben Choud",
    "Dellys",
    "Ammal",
    "Beni Amrane",
    "Souk El Had",
    "Boudouaou El Bahri",
    "Ouled Hedadj",
    "Laghata",
    "Hammedi",
    "Khemis El Khechna",
    "El Kharrouba",
  ],
  [
    "El Tarf",
    "Bouhadjar",
    "Ben Mhidi",
    "Bougous",
    "El Kala",
    "Ain El Assel",
    "El Aioun",
    "Bouteldja",
    "Souarekh",
    "Berrihane",
    "Lac Des Oiseaux",
    "Chefia",
    "Drean",
    "Chihani",
    "Chebaita Mokhtar",
    "Besbes",
    "Asfour",
    "Echatt",
    "Zerizer",
    "Zitouna",
    "Ain Kerma",
    "Oued Zitoun",
    "Hammam Beni Salah",
    "Raml Souk",
  ],
  [
    "Tindouf",
    "Oum El Assel",
  ],
  [
    "Tissemsilt",
    "Bordj Bou Naama",
    "Theniet El Had",
    "Lazharia",
    "Beni Chaib",
    "Lardjem",
    "Melaab",
    "Sidi Lantri",
    "Bordj El Emir Abdelkader",
    "Layoune",
    "Khemisti",
    "Ouled Bessem",
    "Ammari",
    "Youssoufia",
    "Sidi Boutouchent",
    "Larbaa",
    "Maasem",
    "Sidi Abed",
    "Tamalaht",
    "Sidi Slimane",
    "Boucaid",
    "Beni Lahcene",
  ],
  [
    "El Oued",
    "Robbah",
    "Oued El Alenda",
    "Bayadha",
    "Nakhla",
    "Guemar",
    "Kouinine",
    "Reguiba",
    "Hamraia",
    "Taghzout",
    "Debila",
    "Hassani Abdelkrim",
    "Hassi Khelifa",
    "Taleb Larbi",
    "Douar El Ma",
    "Sidi Aoun",
    "Trifaoui",
    "Magrane",
    "Beni Guecha",
    "Ourmas",
    "Still",
    "Mrara",
    "Sidi Khellil",
    "Tendla",
    "El Ogla",
    "Mih Ouansa",
    "El Mghair",
    "Djamaa",
    "Oum Touyour",
    "Sidi Amrane",
  ],
  [
    "Khenchela",
    "Mtoussa",
    "Kais",
    "Baghai",
    "El Hamma",
    "Ain Touila",
    "Taouzianat",
    "Bouhmama",
    "El Oueldja",
    "Remila",
    "Cherchar",
    "Djellal",
    "Babar",
    "Tamza",
    "Ensigha",
    "Ouled Rechache",
    "El Mahmal",
    "Msara",
    "Yabous",
    "Khirane",
    "Chelia",
  ],
  [
    "Souk Ahras",
    "Sedrata",
    "Hanancha",
    "Mechroha",
    "Ouled Driss",
    "Tiffech",
    "Zaarouria",
    "Taoura",
    "Drea",
    "Haddada",
    "Khedara",
    "Merahna",
    "Ouled Moumen",
    "Bir Bouhouche",
    "Mdaourouche",
    "Oum El Adhaim",
    "Ain Zana",
    "Ain Soltane",
    "Quillen",
    "Sidi Fredj",
    "Safel El Ouiden",
    "Ragouba",
    "Khemissa",
    "Oued Keberit",
    "Terraguelt",
    "Zouabi",
  ],
  [
    "Tipaza",
    "Menaceur",
    "Larhat",
    "Douaouda",
    "Bourkika",
    "Khemisti",
    "Aghabal",
    "Hadjout",
    "Sidi Amar",
    "Gouraya",
    "Nodor",
    "Chaiba",
    "Ain Tagourait",
    "Cherchel",
    "Damous",
    "Meurad",
    "Fouka",
    "Bou Ismail",
    "Ahmer El Ain",
    "Bou Haroun",
    "Sidi Ghiles",
    "Messelmoun",
    "Sidi Rached",
    "Kolea",
    "Attatba",
    "Sidi Semiane",
    "Beni Milleuk",
    "Hadjerat Ennous",
  ],
  [
    "Mila",
    "Ferdjioua",
    "Chelghoum Laid",
    "Oued Athmenia",
    "Ain Mellouk",
    "Telerghma",
    "Oued Seguen",
    "Tadjenanet",
    "Benyahia Abderrahmane",
    "Oued Endja",
    "Ahmed Rachedi",
    "Ouled Khalouf",
    "Tiberguent",
    "Bouhatem",
    "Rouached",
    "Tessala Lamatai",
    "Grarem Gouga",
    "Sidi Merouane",
    "Tassadane Haddada",
    "Derradji Bousselah",
    "Minar Zarza",
    "Amira Arras",
    "Terrai Bainen",
    "Hamala",
    "Ain Tine",
    "El Mechira",
    "Sidi Khelifa",
    "Zeghaia",
    "Elayadi Barbes",
    "Ain Beida Harriche",
    "Yahia Beniguecha",
    "Chigara",
  ],
  [
    "Ain Defla",
    "Miliana",
    "Boumedfaa",
    "Khemis Miliana",
    "Hammam Righa",
    "Arib",
    "Djelida",
    "El Amra",
    "Bourached",
    "El Attaf",
    "El Abadia",
    "Djendel",
    "Oued Chorfa",
    "Ain Lechiakh",
    "Oued Djemaa",
    "Rouina",
    "Zeddine",
    "El Hassania",
    "Bir Ouled Khelifa",
    "Ain Soltane",
    "Tarik Ibn Ziad",
    "Bordj Emir Khaled",
    "Ain Torki",
    "Sidi Lakhdar",
    "Ben Allal",
    "Ain Benian",
    "Hoceinia",
    "Barbouche",
    "Djemaa Ouled Chikh",
    "Mekhatria",
    "Bathia",
    "Tachta Zegagha",
    "Ain Bouyahia",
    "El Maine",
    "Tiberkanine",
    "Belaas",
  ],
  [
    "Naama",
    "Mechria",
    "Ain Sefra",
    "Tiout",
    "Sfissifa",
    "Moghrar",
    "Assela",
    "Djeniane Bourzeg",
    "Ain Ben Khelil",
    "Makman Ben Amer",
    "Kasdir",
    "El Biod",
  ],
  [
    "Ain Temouchent",
    "Chaabet El Ham",
    "Ain Kihal",
    "Hammam Bouhadjar",
    "Bou Zedjar",
    "Oued Berkeche",
    "Aghlal",
    "Terga",
    "Ain El Arbaa",
    "Tamzoura",
    "Chentouf",
    "Sidi Ben Adda",
    "Aoubellil",
    "El Malah",
    "Sidi Boumediene",
    "Oued Sabah",
    "Ouled Boudjemaa",
    "Ain Tolba",
    "El Amria",
    "Hassi El Ghella",
    "Hassasna",
    "Ouled Kihal",
    "Beni Saf",
    "Sidi Safi",
    "Oulhaca El Gheraba",
    "Sidi Ouriache",
    "El Emir Abdelkader",
    "El Messaid",
  ],
  [
    "Ghardaia",
    "El Meniaa",
    "Dhayet Bendhahoua",
    "Berriane",
    "Metlili",
    "El Guerrara",
    "El Atteuf",
    "Zelfana",
    "Sebseb",
    "Bounoura",
    "Hassi Fehal",
    "Hassi Gara",
    "Mansoura",
  ],
  [
    "Relizane",
    "Oued Rhiou",
    "Belaassel Bouzegza",
    "Sidi Saada",
    "Ouled Aiche",
    "Sidi Lazreg",
    "El Hamadna",
    "Sidi Mhamed Ben Ali",
    "Mediouna",
    "Sidi Khettab",
    "Ammi Moussa",
    "Zemmoura",
    "Beni Dergoun",
    "Djidiouia",
    "El Guettar",
    "Hamri",
    "El Matmar",
    "Sidi Mhamed Ben Aouda",
    "Ain Tarek",
    "Oued Essalem",
    "Ouarizane",
    "Mazouna",
    "Kalaa",
    "Ain Rahma",
    "Yellel",
    "Oued El Djemaa",
    "Ramka",
    "Mendes",
    "Lahlef",
    "Beni Zentis",
    "Souk El Haad",
    "Dar Ben Abdellah",
    "El Hassi",
    "Had Echkalla",
    "Bendaoud",
    "El Ouldja",
    "Merdja Sidi Abed",
    "Ouled Sidi Mihoub",
  ]
];

List<List<String>> communeArabNameList = [
  [
    "أدرار",
    "تأماست",
    "شروين",
    "رڨان",
    "ان زغمير",
    "تــيـــت",
    "قصر قدور",
    "تسابيت",
    "تيميمون",
    "أولاد سعيد",
    "زاوية كنتة",
    "أولف",
    "تيمقتن",
    "تامنطيت",
    "فنوغيل",
    "زاوية دباغ",
    "دﻟﺪول",
    "سالى",
    "أقبلي",
    "المطارفة",
    "أولاد أحمد تيمى",
    "بودة",
    "أوقروت",
    "",
    "برج باجي مختار",
    "السبع",
    "أولاد عيسى",
    "تيمياوين",
  ],
  [
    "الشلف",
    "تنس",
    "بنايرية",
    "الكريمية",
    "تاجنة",
    "تاوقريت",
    "بني حواء",
    "صبحة",
    "حرشون",
    "أولاد فارس",
    "سيدي عكاشة",
    "بوقدير",
    "بني راشد",
    "تلعصة",
    "الهرنفة",
    "واد ڨوسين",
    "الظهرة",
    "أولاد عباس",
    "سنجاس",
    "الزبوجة",
    "واد سلي",
    "أبو الحسن",
    "المرصى",
    "الشطية",
    "سيدي عبد الرحمان",
    "مصدق",
    "الحجاج",
    "الأبيض مجاجة",
    "واد الفضة",
    "أولاد بن عبد القادر",
    "بوزغاية",
    "عين مران",
    "أم الذروع",
    "بريرة",
    "بني بوعتاب",
  ],
  [
    "الأغواط",
    "قصر الحيران",
    "بن ناصر بن شهرة",
    "سيدي مخلوف",
    "حاسي دلاعة",
    "حاسي الرمل",
    "عــيــن مـــاضــي",
    "تاجموت",
    "الخنق",
    "قلتة سيدي سعد",
    "عين سيدي علي",
    "بيضاء",
    "بريدة",
    "الغيشة",
    "الحاج المشري",
    "سبقاق",
    "تاويالة",
    "تاجرونة",
    "أفلو",
    "العسافية",
    "وادي مرة",
    "وادي مزي",
    "الهوارية",
    "سيدي بوزيد",
  ],
  [
    "أم البواقي",
    "عين البيضاء",
    "عين مليلة",
    "بحير الشرڨي",
    "العامرية",
    "سيقوس",
    "البلالة",
    "عين بابوش",
    "بريش",
    "أولاد حملة",
    "الضلعة",
    "عين كرشة",
    "هنشير تومغني",
    "الجازيـــــــة",
    "عين الديس",
    "فكرينة",
    "سوق نعمان",
    "الزرڨ",
    "الفجوج بوغرارة سعودى",
    "أولاد زواي",
    "بئر الشهداء",
    "قصر صباحي",
    "وادي نيني",
    "مسكيانة",
    "عين فكرون",
    "الراحية",
    "عين الزيتون",
    "أولاد ڨاسم",
    "الحرملية",
  ],
  [
    "باتنة",
    "غسيرة",
    "معافة",
    "مروانة",
    "سريانة",
    "منعة",
    "المعذر",
    "تازولت",
    "نڨاوس",
    "قيقبة",
    "إينوغيسن",
    "عيون العصافير",
    "جرمة",
    "بيطام",
    "عزيل عبد القادر",
    "اريس",
    "كيمل",
    "تيلاطو",
    "عين جاسر",
    "أولاد سلام",
    "تيغرغار",
    "عين ياقوت",
    "فسديس",
    "سفيان",
    "الرحبات",
    "تيغانمين",
    "لمسان",
    "قصر بلازمة",
    "سقانة",
    "ايشمول",
    "فم الطوب",
    "بنى فضالة الحقانية",
    "واد الماء",
    "تالخمت",
    "بوزينة",
    "الشمرة",
    "واد الشعبة",
    "تاكسلانت",
    "القصبات",
    "أولاد عوف",
    "بــومقر",
    "بريكة",
    "الجزار",
    "تكوت",
    "عين التوتة",
    "حيدوسة",
    "نية العابد",
    "وادي الطاقة",
    "أولاد فاضل",
    "تيمقاد",
    "رأس العيون",
    "شير",
    "أولاد سي سليمان",
    "زانة البيضاء",
    "أمدوكال",
    "أولاد عمار",
    "الحاسي",
    "لازرو",
    "بومية",
    "بولهيلات",
    "الاربعاء",
  ],
  [
    "بجاية",
    "اميزور",
    "فرعون",
    "تاوريرت اغيل",
    "شلاطة",
    "تامقرة",
    "تيمزريت",
    "ﺳﻮق اﻻﺛﻨﻴﻦ",
    "مسيسنة",
    "تينبذار",
    "تيشي",
    "سمعون",
    "كنديرة",
    "تيفرة",
    "إغرم",
    "امالو",
    "إغيل على",
    "افناين الماثن",
    "توجة",
    "درقينة",
    "سيدي عياد",
    "أوقاس",
    "آيث جليل",
    "آدكار",
    "أقبو",
    "صدوق",
    "تازمالت",
    "آيت أرزين",
    "شميني",
    "سوق أوفلة",
    "تاسقريوت",
    "طيبان",
    "ثالة حمزة",
    "برباشة",
    "بنى كسيلة",
    "أوزلاقن",
    "بوحمزة",
    "بنى مليكش",
    "سيدي عيش",
    "القصر",
    "ملبو",
    "اكفادو",
    "لفلاى",
    "خراطة",
    "ذراع القايد",
    "تامريجت",
    "آيت سماعيل",
    "بوخليفة",
    "تيزى نبربر",
    "بني معوش",
    "وادي غير",
    "بوجليل",
  ],
  [
    "بسكرة",
    "أوماش",
    "البرانس",
    "شتمة",
    "أولاد جلال",
    "راس الميعاد",
    "البسباس",
    "سيدي خالد",
    "الدوسن",
    "أولاد رحمة",
    "سيدي عقبة",
    "مشونش",
    "الحوش",
    "عين الناقة",
    "زريبة الوادي",
    "الفيض",
    "القنطرة",
    "عين زعطوط",
    "لوطاية",
    "جمورة",
    "طولقة",
    "لواء",
    "لشانة",
    "أورلال",
    "مليلي",
    "فوغالة",
    "برج بن عزوز",
    "مزيرعة",
    "بوشقرون",
    "مخادمة",
    "الغروس",
    "الحاجب",
    "خنڨة سيدي ناجي",
  ],
  [
    "بشار",
    "عرق فراج",
    "أولاد خدير",
    "مريجة",
    "تيمودى",
    "لحمر",
    "بني عباس",
    "بني يخلف",
    "مشرع ھوارى بومدين",
    "القنادسة",
    "إقلي",
    "تبلبالة",
    "تــــاغـيــث",
    "الوطى",
    "بوكايس",
    "موغل",
    "العبادلة",
    "كرزاز",
    "قصابى",
    "تامترت",
    "بني ونيف",
  ],
  [
    "البليدة‎",
    "الشبلي",
    "بوعينان",
    "واد العلايڨ",
    "اولاد يعيش",
    "الشريعة",
    "العفرون",
    "الشفة",
    "حمام ملوان",
    "بني خليل",
    "صومعة",
    "موزاية",
    "صوحان",
    "مفتاح",
    "أولاد سلامة",
    "بوفاريك",
    "الاربعاء",
    "واد جر",
    "بني تامو",
    "بوعرفة",
    "بني مراد",
    "بوڨرة",
    "ڨرواو",
    "عين الرمانة",
    "جبابرة",
  ],
  [
    "البويرة",
    "الأصنام",
    "قرومة",
    "سوق الخميس",
    "قادرية",
    "احنيف",
    "ديــرة",
    "آيت لعزيز",
    "تاغزوت",
    "الروراوة",
    "مسدور",
    "حيزر",
    "الأخضرية",
    "معالة",
    "الھاشمية",
    "أعمر",
    "الشرفاء",
    "برج أوخريص",
    "العجيبة",
    "الحاكمية",
    "الخبوزية",
    "أھل القصر",
    "بودربالة",
    "زبربر",
    "عين الحجر",
    "الجباحية",
    "أغبالو",
    "تاڨديت",
    "عين الترك",
    "الصهاريج",
    "الدشمية",
    "ريدان",
    "بشلول",
    "بوكرام",
    "عين بسام",
    "بئر غبالو",
    "مشدا الله",
    "سور الغزلان",
    "المعمورة",
    "أولاد راشد",
    "عين العلوي",
    "الحجرة الزرقاء",
    "آث منصور",
    "المقراني",
    "وادى البردي",
  ],
  [
    "تمنراست",
    "أبلسة",
    "عـيـن غــار",
    "عين قزام",
    "إدلس",
    "تاظروك",
    "تين زاوتين",
    "عين صالح",
    "ان أمقل",
    "فقارة الزوى",
  ],
  [
    "تبسة",
    "بئر العاتر",
    "الــشــريــعـة",
    "سطح قنطيس",
    "العوينات",
    "الحويجبات",
    "صفصاف الوسرة",
    "الحمامات",
    "نقرين",
    "بــئــر مــقـدم",
    "الكويف",
    "مرسط",
    "العقلة",
    "بٔير الذھب",
    "العقلة",
    "قوريقر",
    "بكارية",
    "بوخضرة",
    "الونزة",
    "الماء الأبيض",
    "أم على",
    "ثليجان",
    "عين الزرقاء",
    "المريج",
    "بولحاف الدير",
    "بجن",
    "المزرعة",
    "فـــــــركـــــان",
  ],
  [
    "تلمسان",
    "بني مستار",
    "عين تالوت",
    "الرمشي",
    "الفحول",
    "صبرة",
    "الغزوات",
    "السواني",
    "جبالة",
    "الغور",
    "وادى الشولى",
    "عين فزّة",
    "أولاد ميمون",
    "عمير",
    "عين يوسف",
    "زناتة",
    "بنى سنوس",
    "باب العسة",
    "دار يغمراسن",
    "فلاوسن",
    "العزايل",
    "سبعة شيوخ",
    "تيرني بني هديل",
    "بن سكران",
    "عين نحالة",
    "الحناية",
    "مغنية",
    "حمام بوغرارة",
    "تونان",
    "مسيردة الفواقة",
    "عين فتاح",
    "العريشة",
    "سوق الثلاثاء",
    "سيدي العبدلي",
    "سبدو",
    "برج عريمة",
    "سيدي مجاهد",
    "بني بوسعيد",
    "مرسى بن مھيدي",
    "ندرومة",
    "سيدي الجيلالي",
    "بني بهدل",
    "البويھي",
    "هنين",
    "تيانت",
    "أولاد رياح",
    "بوحلو",
    "سوق الخميس",
    "عين غرابة",
    "شتوان",
    "المنصورة",
    "بني مستار",
    "عين الكبيرة",
  ],
  [
    "تيارت‎",
    "مدروسة",
    "بوشقيف",
    "سيدي علي ملال",
    "عين زاريت",
    "عين الذهب",
    "سيدي بختي",
    "مدريسة",
    "زمالة الأمير عبد القادر",
    "مادنة",
    "السبت",
    "ملاكو",
    "دحموني",
    "رحوية",
    "المھدية",
    "سوقر",
    "سيدي عبد الغنى",
    "عين الحديد",
    "اولاد جراد",
    "نعيمة",
    "مغيلة",
    "قرطوفة",
    "سيدي حسني",
    "جيلالي بن عمار",
    "سبعين",
    "توسنينة",
    "فرندة",
    "عين كرمس",
    "قصر الشلالة",
    "الرشايقة",
    "ملاكو",
    "تاقدمت",
    "وادى ليلى",
    "مشرع الصفاء",
    "الحمادية",
    "شحيمة",
    "تاخمرت",
    "سيدي عبدالرحمان",
    "سرغين",
    "بوقرة",
    "الفايجة",
    "تيدة",
  ],
  [
    "تيزي وزو",
    "عين الحمام",
    "أقبيل",
    "فريحة",
    "صوامع",
    "مشطراس",
    "إرجن",
    "تيميزارت",
    "ماكودة",
    "ذراع الميزان",
    "تيزي غنيف",
    "بونوح",
    "آيت شفعة",
    "فريقات",
    "بني عيسي",
    "أيت زمنزر",
    "إيفرحونن",
    "عزازقة",
    "إيلولة أمالو",
    "اعكورن",
    "الأربعاء نايت إيراثن",
    "تيزي راشد",
    "زكري",
    "واقنون",
    "عين الزاوية",
    "مكيرة",
    "أيت يحي",
    "أيت محمود",
    "المعاتقة",
    "آيت بومھدى",
    "أبي يوسف",
    "بني دوالة",
    "إليلتن",
    "بوزقن",
    "أيت أقواشة",
    "واضية",
    "أزفون",
    "تقزيرت",
    "آيت عيسى ميمون",
    "بوغني",
    "ايفيغاء",
    "آيت أومالو",
    "ترمتين",
    "أقرو",
    "يطافن",
    "بنى زيكى",
    "ذراع بن خدة",
    "واسيف",
    "آجر",
    "مقلع",
    "تيزي نثلاثة",
    "بني يني",
    "أغريب",
    "إفليسن",
    "بوجيمة",
    "أيت يحي موسى",
    "سوق الإثنين",
    "أيت خليلي",
    "سيدي نعمان",
    "أبودرارن",
    "آقنى قغران",
    "مزرانة",
    "إمسوحال",
    "تادمايت",
    "أيت بوعدو",
    "أسي يوسف",
    "أيت تودرت",
  ],
  [
    "الجزائر الوسطى",
    "سيدي امحمد",
    "المدنية",
    "بلوزداد",
    "باب الواد",
    "بولوغين",
    "القصبة",
    "وادي قريش",
    "بير مراد رايس",
    "الآبيار",
    "بوزريعة",
    "بئر خادم",
    "الحراش",
    "براقي",
    "وادي سمار",
    "بوروبة",
    "حسين داي",
    "القبة",
    "باش جراح",
    "الدار البيضاء",
    "باب الزوار",
    "بن عكنون",
    "دالي ابراهيم",
    "الحمامات",
    "الرايس حميدو",
    "جسر قسنطينة",
    "المرادية",
    "حيدرة",
    "المحمدية",
    "برج الكيفان",
    "المقرية",
    "بني مسوس",
    "الكليتوس",
    "بئر توتة",
    "تسالة المرجة",
    "أولاد الشبل",
    "سيدي موسى",
    "عين طاية",
    "برج البحري",
    "المرسى",
    "هراوة",
    "رويبة",
    "الرغاية",
    "عين بنيان",
    "سطاوالي",
    "زرالدة",
    "محالمة",
    "رحمانية",
    "سويدانية",
    "شراقة",
    "أولاد فايت",
    "العاشور",
    "درارية",
    "دويرة",
    "بابا حسن",
    "خرايسية",
    "السحاولة",
  ],
  [
    "الجلفة",
    "مجبرة",
    "القديد",
    "حاسي بحبح",
    "عين معبد",
    "سد رحال",
    "فيض البطمة",
    "البيرين",
    "بويرة الأحداب",
    "زكار",
    "الخميس",
    "سيدي بايزيد",
    "المليليحة",
    "الإدريسية",
    "الدويس",
    "حاسي العش",
    "مسعد",
    "قتارة",
    "سيدي لعجال",
    "حد الصحاري",
    "القرنيني",
    "سلمانة",
    "عين الشهداء",
    "ام العظام",
    "دار الشيوخ",
    "الشارف",
    "بن يعقوب",
    "الزعفران",
    "دلدول",
    "عين الابل",
    "عين وسارة",
    "بنهار",
    "حاسي فدول",
    "عمورة",
    "عين افقة",
    "تعضميت",
  ],
  [
    "جيجل",
    "إراڨن",
    "العوانة",
    "زيامة منصورية",
    "الطاهير",
    "الامير عبد القادر",
    "الشقفة",
    "الشحنة",
    "الميلية",
    "سيدي معروف",
    "السطارة",
    "العنصر",
    "سيدي عبد العزيز",
    "قاوس",
    "غبالة",
    "بوراوي بلهادف",
    "جيملة",
    "سلمى بن زيادة",
    "أولاد عسكر",
    "القنار",
    "اولاد يحيى",
    "بودريعة بن ياجيس",
    "بني بلعيد",
    "تاكسنة",
    "الجمعة بني حبيبي",
    "برج الطهر",
    "ولاد رابح",
    "وجانة",
  ],
  [
    "سطيف‎",
    "عين الكبيرة",
    "بني عزيز",
    "أولاد سي أحمد",
    "بوطالب",
    "عين الروى",
    "ذراع قبيلة",
    "بئر العرش",
    "بني شبانة",
    "أولاد تبــان",
    "حــامة",
    "معـاويـة",
    "عين لڨراج",
    "عين عباسـة",
    "الدهامشة",
    "بابور",
    "قجــال",
    "عين لحجـر",
    "بوسلام",
    "العلمة",
    "جميلـة",
    "بني ورتيلان",
    "الرصفة",
    "أولاد عدوان",
    "البلاعة",
    "عين أرنـات",
    "عموشة",
    "عين ولمان",
    "بيضاء برج",
    "بوعنداس",
    "بازر الصخرة",
    "حمــام السخنة",
    "مزلوق",
    "بئر حدادة",
    "سرج الغول",
    "حربيل",
    "الأورسية",
    "تيزي نبشار",
    "صـالح باي",
    "عين أزال",
    "ڨنزات",
    "تالة إيفاسن",
    "بوقاعـة",
    "بني فودة",
    "تاشودة",
    "إيث موحلي",
    "أولاد صـابر",
    "قلال",
    "عين السبت",
    "حمام قرقور",
    "آيت نوال مزادة",
    "قصرالأبطال",
    "بني حسين",
    "آيت تيزي",
    "موكلان",
    "القلتة الزرقاء",
    "واد البارد",
    "طاية",
    "الولجـة",
    "التلة",
  ],
  [
    "سعيدة",
    "دوى ثابت",
    "عين الحجر",
    "أولاد خالد",
    "موالي العربي",
    "يوب",
    "هونت",
    "يدي عمر",
    "سيدي بوبكر",
    "حساسنة",
    "معمورة",
    "سيدي أحمد",
    "العين السخونة",
    "أولاد ابراھيم",
    "تيرسين",
    "عين السلطان",
  ],
  [
    "سكيكدة",
    "عين زويت",
    "الحدايق",
    "عزابة",
    "جندل",
    "عين شرشار",
    "بكوش لخضر",
    "بن عزوز",
    "السبت",
    "القل",
    "بنى زيد",
    "كركرة",
    "أولاد عطية",
    "وادي الزهور",
    "الزيتونة",
    "الحروش",
    "زردازة",
    "أولاد حبابة",
    "سيدي مزغيش",
    "مجاز الدشيش",
    "بني والبان",
    "عين بوزيان",
    "رمضان جمال",
    "بني بشير",
    "صالح بوالشعور",
    "تمالوس",
    "عين قشرة",
    "أم الطوب",
    "بين الويدان",
    "فلفلة",
    "الشرايع",
    "قنواع",
    "الغدير",
    "بوشطاطة",
    "الولجة بو البلوط",
    "خنق مايوم",
    "حمادي كرومة",
    "المرسى",
  ],
  [
    "سيدي بلعباس",
    "تسالة",
    "سيدي ابراهيم",
    "مصطفى بن ابراهيم",
    "تلاغ",
    "مزاورو",
    "بوخنفيس",
    "سيدي علي بوسيدي",
    "بدر الدين المقراني",
    "مرحوم",
    "تفسور",
    "العمارنة",
    "تلموني",
    "سيدي لحسن",
    "عين التريد",
    "مكدرة",
    "تنيرة",
    "مولاي سليسن",
    "الحصيبة",
    "حاسي زهانة",
    "طابية",
    "مرين",
    "رأس الماء",
    "عين تندامين",
    "عين قادة",
    "مسيد",
    "سيدي خالد",
    "عين البرد",
    "سفيزف",
    "عين عدان",
    "واد تاوريرة",
    "الظاية",
    "زروالة",
    "لمطار",
    "سيدي شعيب",
    "سيدي دحو",
    "واد السبع",
    "بوجبهة البرج",
    "سهالة الثورة",
    "سيدي يعقوب",
    "سيدي حمادوش",
    "بلعربي",
    "واد سفيون",
    "تغاليمت",
    "ابن باديس",
    "سيدي علي بن يوب",
    "شطوان بلايلة",
    "بئر الحمام",
    "تاودموت",
    "رجم دموش",
    "بن عشيبة شلية",
    "حاسي دحو",
  ],
  [
    "عنابة",
    "برحال",
    "الحجار",
    "العلمة",
    "البوني",
    "وادي العنب",
    "الشرفة",
    "سرايدي",
    "عين الباردة",
    "شطايبي",
    "سيدي عمار",
    "التريعات",
  ],
  [
    "قالمة",
    "نشماية",
    "بوعاتي محمود",
    "وادي الزناتي",
    "تاملوكة",
    "وادي فراغة",
    "عين صندل",
    "راس العقبة",
    "الدهوارة",
    "بلخير",
    "بن جراح",
    "بوحمدان",
    "عين مخلوف",
    "عين بن بيضاء",
    "خزارة",
    "بني مزلين",
    "بوحشانة",
    "قلعة بوصبع",
    "حمام مسخوطين",
    "الفجوج",
    "برج صباط",
    "حمام النبايل",
    "عين العربى",
    "مجاز عمار",
    "بوشقوف",
    "ھيليوبوليس",
    "هواري بومدين",
    "الركنية",
    "سلاوة عنونة",
    "مجاز الصفاء",
    "بومهرة أحمد",
    "عين رقادة",
    "وادي الشحم",
    "جبالة لخميسي",
  ],
  [
    "قسنطينة",
    "حامة بوزيان",
    "إبن باديس",
    "زيغود يوسف",
    "ديدوش مراد",
    "الخروب",
    "عين عبيد",
    "بني حميدان",
    "أولاد رحمون",
    "عين سمارة",
    "مسعود بوجريو",
    "ابن زياد",
  ],
  [
    "المدية",
    "وزرة",
    "أولاد معرف",
    "عين بوسيف",
    "العيساوية",
    "أولاد دايد",
    "العمارية",
    "دراڨ",
    "القلب الكبير",
    "بوعيش",
    "مزغنة",
    "أولاد إبراهيم",
    "تيزي المهدي",
    "سيدي زيان",
    "تمزڨيدة",
    "الحمدانية",
    "الكاف الأخضر",
    "شلالة العذاورة",
    "بوسكن",
    "الربعية",
    "بوشراحيل",
    "أولاد هلال",
    "تافراوت",
    "بعطة",
    "بوغار",
    "سيدي نعمان",
    "أولاد بوعشرة",
    "سيدي زهار",
    "وادي حربيل",
    "بن شكاو",
    "سيدي دامد",
    "عزيز",
    "السواڨي",
    "الزبيرية",
    "قصر البخاري",
    "العزيزية",
    "جواب",
    "الشهبونية",
    "مغراوة",
    "شنيڨل",
    "عين القصير",
    "أم الجليل",
    "عوامري",
    "سى المحجوب",
    "ثلاثة الدوائر",
    "بني سليمان",
    "البرواڨية",
    "سغوان",
    "المفاتحة",
    "ميهوب",
    "بوغزول",
    "تابلاط",
    "فج الحوضين",
    "ذراع السمار",
    "سيدي الربيع",
    "بئر بن العابد",
    "العوينات",
    "أولاد عنتر",
    "بوعيشون",
    "حناشة",
    "سدراية",
    "مجبر",
    "خمس جوامع",
    "سانڨ",
  ],
  [
    "مستغانم",
    "صيادة",
    "فرناكة",
    "ستيدية",
    "عين نويسي",
    "حاسي مماش",
    "عين تادلس",
    "صور",
    "واد الخير",
    "سيدي بلعاتر",
    "خير الدين",
    "سيدي علي",
    "عبد المالك رمضان",
    "حجاج",
    "نقمارية",
    "سيدي لخضر",
    "عشعاشة",
    "خضراء",
    "بوقيراط",
    "سيرات",
    "عين سيدي شريف",
    "ماسرة",
    "منصورة",
    "سوافلية",
    "أوالد بوغالم",
    "أولاد مع اللّه",
    "مزغران",
    "عين بودينار",
    "تزقايت",
    "صفصاف",
    "طواھيرية",
    "الحسيان",
  ],
  [
    "المسيلة",
    "المعاضيد",
    "حمـام الضلعة",
    "أولاد دراج",
    "تارمونت",
    "مطارفة",
    "خبانة",
    "مسيف",
    "شلال",
    "أولاد مـاضي",
    "مقرة",
    "برهوم",
    "عين الخضراء",
    "اولاد عدي لقبالة",
    "بلعايبة",
    "سيدي عيسى",
    "عين الحجل",
    "سيدي ھجرس",
    "ونوغة",
    "بوسعادة",
    "أولاد سيدي ابراهيم",
    "سيدي عامر",
    "تامسة",
    "بن سرور",
    "أولاد سليمان",
    "الحوامد",
    "الهامل",
    "أولاد منصور",
    "المعاريف",
    "الدهاهنة",
    "بوطي السايح",
    "خطوطي سد الجير",
    "الزرزور",
    "محمد بوضياف",
    "بن الزوه",
    "بير الفضة",
    "عين فارس",
    "سيدي محمد",
    "منعة",
    "الصوامع",
    "عين الملح",
    "مجدل",
    "سليم",
    "عين الريش",
    "بنى يلمان",
    "ولتام",
    "جبل مساعد",
  ],
  [
    "مـعـسـكـر",
    "بوحنيفية",
    "تيزي",
    "حسين",
    "ماوسة",
    "تيغنيف",
    "الهاشم",
    "سيدي قادة",
    "زلماطة",
    "واد الأبطال",
    "عين فراح",
    "غريس",
    "فروحة",
    "مطمور",
    "ماقضة",
    "سيدي بوسعيد",
    "البرج",
    "عين فكان",
    "بنيان",
    "خلوية",
    "المناور",
    "واد التاغية",
    "عوف",
    "عين فارس",
    "عين فراس",
    "سيڨ",
    "عقاز",
    "العلايمية",
    "القعدة",
    "زھانة",
    "المحمدية",
    "سيدي عبد المومن",
    "فرقيق",
    "الغمري",
    "سجرارة",
    "مقطع الدوز",
    "بوهني",
    "القيطنة",
    "المامونية",
    "الكرط",
    "غروس",
    "ڤرجوم",
    "الشرفة",
    "رأس العين عميروش",
    "نسموط",
    "سيدي عبد الجبار",
    "سحايلية",
  ],
  [
    "ورڨلة",
    "عين البيضاء",
    "نقوسة",
    "حاسي مسعود",
    "الرويسات",
    "بليدة عامر",
    "تبسبست",
    "نزلة",
    "الزاوية العابدية",
    "سيدي سليمان",
    "سيدي خويلد",
    "حاسي بن عبد ﷲ",
    "توقرت",
    "الحجيرة",
    "الطيبات",
    "تماسين",
    "بن ناصر",
    "المنقر",
    "المقارين",
    "العالية",
    "البرمة",
  ],
  [
    "وهران",
    "ڨديل",
    "بئر الجير",
    "حاسيْ بُونِيف",
    "السانية",
    "أرزيو",
    "ﺑﻃﻴﻭة",
    "مَرس ألحَجَاج",
    "عيْن التُرْكْ",
    "العنصر",
    "وادى تليلات",
    "طفراوي",
    "سيدي الشحمي",
    "بوفاطيس",
    "المرسى الكبير",
    "بوسفر",
    "الكرمة",
    "ألبْرَيَ",
    "حاسي بن عقبة",
    "بن فريحة",
    "حاسي مفسوخ",
    "سيدي بن يبقى",
    "مسرغين",
    "بوتليليس",
    "عين الكرمة",
    "عين البية",
  ],
  [
    "الـبـيـض",
    "روقاصة",
    "ستيتين",
    "بريزينة",
    "غسول",
    "بوعلام",
    "الابيض سيدي الشيخ",
    "عين العراك",
    "أربوات",
    "بوقطب",
    "الخيثر",
    "الكاف الاحمر",
    "بوسمغون",
    "شلالة",
    "كراكدة",
    "البنود",
    "الشقيق",
    "سيدي عامر",
    "المھارة",
    "توسمولين",
    "سيدي سليمان",
    "سيدي طيفور",
  ],
  [
    "إلـيـزي",
    "جانت",
    "دبداب",
    "برج عمر ادريس",
    "برج الحواس",
    "إن أميناس",
  ],
  [
    "برج بوعريريج",
    "رأس الوادي",
    "برج زمورة",
    "منصورة",
    "المھير",
    "بن داود",
    "العشير",
    "عين تاغروت",
    "برج غدير",
    "سيدي مبارك",
    "الحمادية",
    "بليمور",
    "مجانة",
    "ثنية النصر",
    "جعافرة",
    "إلماين",
    "أولاد ابراھم",
    "أولاد دحمان",
    "حسناوة",
    "خليل",
    "تاقلعيت",
    "القصور",
    "آث سيذى پراهم.",
    "تفرڨ",
    "القلة",
    "تقصطر",
    "العش",
    "العناصر",
    "تسمارت",
    "عين تسرة",
    "بئر قصد علي",
    "غيلاسة",
    "الرابطة",
    "الحرازة",
  ],
  [
    "بومرداس",
    "بودواو",
    "أفير",
    "برج منايل",
    "بغلية",
    "سيدي داود",
    "الناصرية",
    "جنات",
    "يسر",
    "زموري",
    "سي مصطفى",
    "تيجلابين",
    "شعبة العامر",
    "الثنية",
    "تمزريت",
    "قورصو",
    "أولاد موسى",
    "الأربعطاش",
    "بوزقزة قدارة",
    "تورقة",
    "أولاد عيسى",
    "بن شود",
    "دلس",
    "عمال",
    "بنى عمران",
    "سوق الحد",
    "بودواو البحرى",
    "أولاد ھداج",
    "لقاطة",
    "حمادى",
    "خميس الخشنة",
    "الخروبة",
  ],
  [
    "الطارف",
    "بوحجار",
    "بن مهيدى",
    "بوقوس",
    "القالة",
    "عين العسل",
    "العيون",
    "بوثلجة",
    "السوارخ",
    "برحان",
    "بحيرة الطيور",
    "الشافية",
    "الذرعان",
    "شهانى",
    "شبيطة مختار",
    "البسباس",
    "عصفور",
    "الشط",
    "زريزر",
    "الزيتونة",
    "عين الكرمة",
    "وادى الزيتون",
    "حمام بنى صالح",
    "رمل سوق",
  ],
  [
    "تندوف",
    "أم العسل",
  ],
  [
    "تـيـسـمـسـيـلـت",
    "برج بونعامة",
    "ثنية الاحد",
    "الازھرية",
    "بنى شعيب",
    "لارجم",
    "ملعب",
    "سيدي العنترى",
    "برج الامير عبد القادر",
    "العيون",
    "خميستى",
    "أولاد بسام",
    "عمارى",
    "اليوسفية",
    "سيدي بوتوشنت",
    "الاربعاء",
    "المعاصم",
    "سيدي عابد",
    "تاملاحت",
    "سيدي سليمان",
    "بوقايد",
    "بنى لحسن",
  ],
  [
    "الوادي",
    "رباح",
    "وادى العلندة",
    "البياضة",
    "النخلة",
    "ڨمار",
    "كوينين",
    "الرڨيبة",
    "الحمراية",
    "تغزوت",
    "الدبيلة",
    "بلدية حساني عبد الكريم",
    "حاسى خليفة",
    "طالب العربي",
    "دوار الماء",
    "سيدي عون",
    "تريفاوى",
    "المڨرن",
    "بن ڨشة",
    "أورماس",
    "سطيل",
    "مرارة",
    "سيدي خليل",
    "تندلة",
    "العقلة",
    "مية ونسة",
    "المغير",
    "جامعة",
    "أم الطيور",
    "سيدي عمران",
  ],
  [
    "خنشلة",
    "متوسة",
    "قايس",
    "بغاي",
    "الحامة",
    "عين الطويلة",
    "تاوزيانت",
    "بوحمامة",
    "الولجة",
    "الرميلة",
    "ششار",
    "جلال",
    "بابار",
    "تامزة",
    "انسيغة",
    "أولاد رشاش",
    "المحمل",
    "أمصارة",
    "يابوس",
    "خيران",
    "شلية",
  ],
  [
    "سوق أهراس",
    "سدراتة",
    "الحنانشة",
    "المشروحة",
    "أولاد ادريس",
    "تيفاش",
    "الزعرورية",
    "تاورة",
    "الدريعة",
    "الحدادة",
    "لخضارة",
    "المراهنة",
    "أولاد مؤمن",
    "بئر بوحوش",
    "مداوروش",
    "أم العظائم",
    "عين الزانة",
    "عين السلطان",
    "ويلان",
    "سيدي فرج",
    "سافل الويدان",
    "الرقوبة",
    "خميسة",
    "وادى الكبريت",
    "ترقالت",
    "الزوابى",
  ],
  [
    "تيبازة",
    "مناصر",
    "الأرهاط",
    "دواودة",
    "بورقيقة",
    "خميستي",
    "أغابال",
    "حجوط",
    "سيدي عمر",
    "ڨورايا",
    "الناظور",
    "الشعيبة",
    "عين تڨورايت",
    "شرشال",
    "الداموس",
    "مراد",
    "فوكة",
    "بو اسماعيل",
    "أحمر العين",
    "بوهارون",
    "سيدي غيلاس",
    "مسلمون",
    "سيدي راشد",
    "القليعة",
    "الحطاطبة",
    "سيدي سميان",
    "بني ميلك",
    "حجرة النص",
  ],
  [
    "ميلة",
    "فرجيوة",
    "شلغوم العيد",
    "وادي العثمانية",
    "عين ملوك",
    "تلاغمة",
    "وادى سقان",
    "تاجنانت",
    "بن يحيى عبد الرحمان",
    "وادى النجاء",
    "أحمد راشدي",
    "أولاد خلوف",
    "تيبرقنت",
    "بوحاتم",
    "رواشد",
    "تسالة لمطاي",
    "القرارم قوقة",
    "سيدي مروان",
    "تسدان حدادة",
    "دراحي بوصلاح",
    "مينار زرزة",
    "عميرة أراس",
    "ترعى بينان",
    "حمالة",
    "عين التين",
    "المشيرة",
    "سيدي خليفة",
    "زغاية",
    "العياضى برباس",
    "عين البيضاء حريش",
    "يحيى بنى قشة",
    "الشيقارة",
  ],
  [
    "عين دفلة - عين الدفلى",
    "مليانة",
    "بومدفع",
    "خميس مليانة",
    "حمام ريغة",
    "عريب",
    "جليدة",
    "العامرة",
    "بوراشد",
    "العطاف",
    "العبادية",
    "جندل",
    "وادى الشرفاء",
    "عين االشياخ",
    "وادى جمعة",
    "روينة",
    "زدين",
    "الحسنية",
    "بئر ولد خليفة",
    "عين السلطان",
    "طارق بن زياد",
    "برج الأمير خالد",
    "عين التركى",
    "سيدي لخضر",
    "بن علال",
    "عين البنيان",
    "حسينية",
    "بربوش",
    "جمعة أولاد الشيخ",
    "المخاطرية",
    "بطحية",
    "تاشتة زقاغة",
    "عين بويحى",
    "الماين",
    "تبركانين",
    "بالعاص",
  ],
  [
    "النــعـامـة",
    "مشرية",
    "عين الصفراء",
    "تيوت",
    "صفيصيفة",
    "مغرار",
    "عسلة",
    "جنين بورزق",
    "عين بن خليل",
    "مكمن بن عمر",
    "قصدير",
    "البيوض",
  ],
  [
    "عـيـن تـمـوشـنـت",
    "شعبة اللحم",
    "عين الكيحل",
    "حمام بو حجر",
    "بوزجار",
    "وادى برقش",
    "أغلال",
    "تارقة",
    "عين الاربعاء",
    "تامزوغة",
    "شنتوف",
    "سيدي بن عدة",
    "عقب الليل",
    "المالح",
    "سيدي بومدين",
    "وادى الصباح",
    "أولاد بوجمعة",
    "عين الطلبة",
    "العامرية",
    "حاسى الغلة",
    "الحساسنة",
    "أولاد الكيحل",
    "بني صاف",
    "سيدي الصافي",
    "ولهاصة الغرابة",
    "سيدي وريلش",
    "الأمير عبد القادر",
    "المساعيد",
  ],
  [
    "غرداية",
    "المنيعة",
    "ضاية بن ضحوة",
    "بريان",
    "متليلي الشعانبة",
    "الڨرارة",
    "العطف",
    "زلفانة",
    "سبسب",
    "بونورة",
    "حاسي الفحل",
    "حاسي قارة",
    "منصورة",
  ],
  [
    "غيليزان",
    "وادي رهيو",
    "بلعسل بوزقزة",
    "سيدي سعادة",
    "أولاد يعيش",
    "سيدي لزرق",
    "الحمادنة",
    "سيدي امحمد بن علي",
    "مديونة",
    "سيدي خطاب",
    "عمي موسى",
    "زمورة",
    "بني درقن",
    "جيديوة",
    "القطارة",
    "الحمري",
    "المطمار",
    "سيدي بن عودة",
    "عين طارق",
    "وادي السلام",
    "ﻭﺍﺭﻳﺯﺍﻥ",
    "مازونة",
    "قلعة",
    "عين الرحمة",
    "يلل",
    "وادى الجمعة",
    "رمكة",
    "مندس",
    "لحلاف",
    "بني زنتيس",
    "سوق الحد",
    "دار بن عبد الله",
    "الحاسى",
    "حد الشقالة",
    "بن داود",
    "العلجة",
    "مرجة سيدي عابد",
    "أولاد سيدي ميهوب",
  ]
];
