Set jobCategories = {
  "Agriculture, Food and Natural Resources",
  "Architecture and Construction",
  "Arts, Audio/Video Technology and Communications",
  "Business Management and Administration",
  "Education and Training",
  "Finance",
  "Government and Public Administration",
  "Health Science",
  "Hospitality and Tourism",
  "Human Services",
  "Information Technology",
  "Law, Public Safety, Corrections and Security",
  "Manufacturing",
  "Marketing, Sales and Service",
  "Science, Technology, Engineering and Mathematics",
  "Transportation, Distribution and Logistics",
};

Set JobTitles = {
  "Electrical Engineer",
  "Senior Financial Analyst",
  "Statistician III",
  "Software Consultant",
  "Social Worker",
  "VP Marketing",
  "Account Coordinator",
  "Analyst Programmer",
  "Project Manager",
  "Programmer III",
  "Automation Specialist II",
  "Community Outreach Specialist",
  "Registered Nurse",
  "Technical Writer",
  "Nurse Practicioner",
  "Legal Assistant",
  "Research Nurse",
  "Structural Engineer",
  "Payment Adjustment Coordinator",
  "Nuclear Power Engineer",
  "Accounting Assistant II",
  "Senior Sales Associate",
  "Editor",
  "Food Chemist",
  "Chemical Engineer",
  "Media Manager II",
  "Accountant II",
  "Engineer III",
  "Actuary",
  "Compensation Analyst",
  "Pharmacist",
  "Librarian",
  "Dental Hygienist",
  "Marketing Manager",
  "VP Quality Control",
  "General Manager",
  "Financial Advisor",
  "Paralegal",
  "Geological Engineer",
  "Staff Scientist",
  "Occupational Therapist",
  "Desktop Support Technician",
  "Human Resources Manager",
  "GIS Technical Architect",
  "Senior Cost Accountant",
  "Nurse",
  "Administrative Assistant II",
  "Data Coordiator",
  "Assistant Manager",
  "Staff Accountant I",
  "Environmental Tech",
  "Programmer Analyst I",
  "Junior Executive",
  "Help Desk Operator",
  "Computer Systems Analyst III",
  "Information Systems Manager",
  "Structural Analysis Engineer",
  "Administrative Officer",
  "Marketing Assistant",
  "Social Worker",
  "Paralegal",
  "Mechanical Systems Engineer",
  "Actuary",
  "Payment Adjustment Coordinator",
  "Internal Auditor",
  "Software Engineer IV",
  "Web Designer III",
  "Systems Administrator II",
  "Biostatistician I",
  "Librarian",
  "Community Outreach Specialist",
  "Accountant III",
  "Speech Pathologist",
  "Engineer II",
  "Geologist I",
  "Human Resources Assistant III",
  "Civil Engineer",
  "Graphic Designer",
  "Geologist IV",
  "Programmer Analyst IV",
  "Accounting Assistant IV",
  "Account Executive",
  "Assistant Professor",
  "Cost Accountant",
  "Accounting Assistant I",
  "Product Engineer",
  "Operator",
  "Office Assistant I",
  "Sales Representative",
  "VP Product Management",
  "Research Assistant III",
  "Software Test Engineer III",
  "Sales Associate",
  "Physical Therapy Assistant",
  "Account Representative II",
  "Research Associate",
  "Associate Professor",
  "Systems Administrator I",
  "Clinical Specialist",
  "Senior Developer",
  "VP Accounting",
  "Project Manager",
  "Marketing Assistant",
  "Desktop Support Technician",
  "Editor",
  "Human Resources Assistant I",
  "Administrative Officer",
  "Software Engineer II",
  "Recruiter",
  "Data Coordiator",
  "Desktop Support Technician",
  "Quality Control Specialist",
  "Senior Developer",
  "Geological Engineer",
  "Structural Engineer",
  "Assistant Professor",
  "Mechanical Systems Engineer",
  "Software Test Engineer IV",
  "VP Sales",
  "Web Designer I",
  "Payment Adjustment Coordinator",
  "Registered Nurse",
  "Sales Representative",
  "Civil Engineer",
  "Business Systems Development Analyst",
  "VP Quality Control",
  "Accountant IV",
  "Safety Technician III",
  "Teacher",
  "Dental Hygienist",
  "Assistant Manager",
  "VP Accounting",
  "Software Engineer I",
  "Assistant Media Planner",
  "VP Marketing",
  "Staff Scientist",
  "Chemical Engineer",
  "Geological Engineer",
  "Staff Scientist",
  "Account Representative II",
  "General Manager",
  "Executive Secretary",
  "Computer Systems Analyst I",
  "Automation Specialist I",
  "Environmental Specialist",
  "Tax Accountant",
  "Marketing Assistant",
  "Account Representative I",
  "Accounting Assistant II",
  "Engineer I",
  "VP Marketing",
  "Account Coordinator",
  "Librarian",
  "Environmental Tech",
  "Paralegal",
  "Director of Sales",
  "Chief Design Engineer",
  "Editor",
  "Business Systems Development Analyst",
  "Nurse Practicioner",
  "Associate Professor",
  "VP Accounting",
  "Human Resources Assistant II",
  "Database Administrator III",
  "Senior Financial Analyst",
  "Tax Accountant",
  "Registered Nurse",
  "Web Designer II",
  "Tax Accountant",
  "Marketing Manager",
  "Research Associate",
  "Food Chemist",
  "Programmer III",
  "Account Representative II",
  "Librarian",
  "Cost Accountant",
  "General Manager",
  "Statistician II",
  "Civil Engineer",
  "Internal Auditor",
  "Staff Accountant II",
  "Staff Accountant I",
  "Speech Pathologist",
  "Software Consultant",
  "Research Nurse",
  "Staff Accountant II",
  "Database Administrator III",
  "Nurse Practicioner",
  "Systems Administrator II",
  "Physical Therapy Assistant",
  "Professor",
  "Administrative Officer",
  "Assistant Professor",
  "Analyst Programmer",
  "Administrative Assistant II",
  "Recruiter",
  "Environmental Tech",
  "Associate Professor",
  "Occupational Therapist",
  "Administrative Assistant IV",
  "VP Product Management",
  "Assistant Manager",
  "Accountant I",
  "Cost Accountant",
  "VP Quality Control",
  "Junior Executive",
  "Executive Secretary",
  "Office Assistant IV",
  "Tax Accountant",
  "Help Desk Operator",
  "Help Desk Operator",
  "Health Coach II",
  "Account Representative III",
  "Help Desk Operator",
  "Environmental Tech",
  "Chemical Engineer",
  "Database Administrator IV",
  "VP Product Management",
  "VP Sales",
  "Paralegal",
  "Programmer Analyst IV",
  "Internal Auditor",
  "Editor",
  "Analog Circuit Design manager",
  "Environmental Tech",
  "VP Sales",
  "Clinical Specialist",
  "Safety Technician III",
  "VP Sales",
  "Media Manager II",
  "Human Resources Manager",
  "Health Coach I",
  "Health Coach I",
  "Technical Writer",
  "Registered Nurse",
  "Project Manager",
  "Structural Analysis Engineer",
  "Paralegal",
  "Technical Writer",
  "Quality Control Specialist",
  "GIS Technical Architect",
  "Recruiting Manager",
  "Assistant Professor",
  "Account Executive",
  "Help Desk Operator",
  "VP Accounting",
  "Recruiter",
  "Engineer IV",
  "Media Manager IV",
  "Software Test Engineer I",
  "Nurse",
  "Senior Financial Analyst",
  "Geological Engineer",
  "Professor",
  "Occupational Therapist",
  "VP Quality Control",
  "Systems Administrator IV",
  "Professor",
  "Payment Adjustment Coordinator",
  "Registered Nurse",
  "Software Consultant",
  "Pharmacist",
  "Recruiter",
  "Director of Sales",
  "Junior Executive",
  "Social Worker",
  "Marketing Assistant",
  "Automation Specialist IV",
  "Biostatistician II",
  "Automation Specialist IV",
  "Associate Professor",
  "VP Product Management",
  "Geologist III",
  "Software Consultant",
  "Programmer II",
  "Marketing Assistant",
  "Professor",
  "Paralegal",
  "Teacher",
  "Sales Representative",
  "Health Coach II",
  "Safety Technician II",
  "Web Developer I",
  "Quality Control Specialist",
  "Chemical Engineer",
  "Quality Engineer",
  "Systems Administrator IV",
  "Legal Assistant",
  "Biostatistician II",
  "Senior Quality Engineer",
  "Senior Cost Accountant",
  "General Manager",
  "Sales Representative",
  "Senior Quality Engineer",
  "Food Chemist",
  "Environmental Tech",
  "Programmer Analyst III",
  "Assistant Professor",
  "Assistant Manager",
  "Product Engineer",
  "Account Executive",
  "Technical Writer",
  "Safety Technician II",
  "Biostatistician II",
  "Structural Engineer",
  "Account Executive",
  "Tax Accountant",
  "Legal Assistant",
  "Technical Writer",
};
